config/routes.rb
Rails.application.routes.draw do
  resources :payments

  resources :order_accessories

  resources :accessories

  resources :orders

  resources :cars

  devise_for :users
  resources :users

  root 'orders#index'

end

app/models/order_accessory.rb
class OrderAccessory < ActiveRecord::Base
  belongs_to :order
  belongs_to :accessory
end

app/controllers/order_accessories_controller.rb
class OrderAccessoriesController < ApplicationController
  before_action :set_order_accessory, only: [:show, :edit, :update, :destroy]

  # GET /order_accessories
  # GET /order_accessories.json
  def index
    @order_accessories = OrderAccessory.all
  end

  # GET /order_accessories/1
  # GET /order_accessories/1.json
  def show
  end

  # GET /order_accessories/new
  def new
    @order_accessory = OrderAccessory.new
  end

  # GET /order_accessories/1/edit
  def edit
  end

  # POST /order_accessories
  # POST /order_accessories.json
  def create
    @order_accessory = OrderAccessory.new(order_accessory_params)

    respond_to do |format|
      if @order_accessory.save
        format.html { redirect_to @order_accessory, notice: 'Order accessory was successfully created.' }
        format.json { render :show, status: :created, location: @order_accessory }
      else
        format.html { render :new }
        format.json { render json: @order_accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_accessories/1
  # PATCH/PUT /order_accessories/1.json
  def update
    respond_to do |format|
      if @order_accessory.update(order_accessory_params)
        format.html { redirect_to @order_accessory, notice: 'Order accessory was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_accessory }
      else
        format.html { render :edit }
        format.json { render json: @order_accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_accessories/1
  # DELETE /order_accessories/1.json
  def destroy
    @order_accessory.destroy
    respond_to do |format|
      format.html { redirect_to order_accessories_url, notice: 'Order accessory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_accessory
      @order_accessory = OrderAccessory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_accessory_params
      params.require(:order_accessory).permit(:accessory_id, :count)
    end
end

app/views/order_accessories/_form.html.erb
<%= form_for(@order_accessory) do |f| %>
  <% if @order_accessory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_accessory.errors.count, "error") %> prohibited this order_accessory from being saved:</h2>

      <ul>
      <% @order_accessory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :accessory_id %><br>
    <%= f.number_field :accessory_id %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_accessories/edit.html.erb
<h1>Editing order_accessory</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_accessory %> |
<%= link_to 'Back', order_accessories_path %>

app/views/order_accessories/index.html.erb
<h1>Listing order_accessories</h1>

<table>
  <thead>
    <tr>
      <th>Accessory</th>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_accessories.each do |order_accessory| %>
      <tr>
        <td><%= order_accessory.accessory_id %></td>
        <td><%= order_accessory.count %></td>
        <td><%= link_to 'Show', order_accessory %></td>
        <td><%= link_to 'Edit', edit_order_accessory_path(order_accessory) %></td>
        <td><%= link_to 'Destroy', order_accessory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order accessory', new_order_accessory_path %>

app/views/order_accessories/new.html.erb
<h1>New order_accessory</h1>

<%= render 'form' %>

<%= link_to 'Back', order_accessories_path %>

app/views/order_accessories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Accessory:</strong>
  <%= @order_accessory.accessory_id %>
</p>

<p>
  <strong>Count:</strong>
  <%= @order_accessory.count %>
</p>

<%= link_to 'Edit', edit_order_accessory_path(@order_accessory) %> |
<%= link_to 'Back', order_accessories_path %>