config/routes.rb
Rails.application.routes.draw do
  resources :payments

  resources :order_accessories

  resources :accessories

  resources :orders

  resources :cars

  devise_for :users
  resources :users

  root 'orders#index'

end

app/views/shared/_account.html.erb
<!-- BEGIN USER LOGIN DROPDOWN -->
<li class="dropdown dropdown-user">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
  <span class="username">
  <% if current_user.email.blank?  %>
    <%= current_user.email %>
  <% else %>
    <%= current_user.email %>
  <% end %>
  </span>
  <i class="fa fa-angle-down"></i>
  </a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to "#" do %>
      <i class="icon-user"></i> 修改密码
      <% end %>
    </li>
    <li class="divider">
    </li>
    <li>
      <%= link_to destroy_user_session_path, { method: "delete", rel: "nofollow" } do %>
      <i class="icon-key"></i> 注销
      <% end %>
    </li>
  </ul>
</li>
<!-- END USER LOGIN DROPDOWN -->

app/views/shared/_column.html.erb
<label class="control-label col-md-1"><%= name %></label>
<div class="col-md-3">
  <%= content %>
</div>

app/views/shared/_column_double.html.erb
<label class="control-label col-md-1"><%= name %></label>
<div class="col-md-7">
  <%= content %>
</div>

app/views/shared/_column_triple.html.erb
<label class="control-label col-md-1"><%= name %></label>
<div class="col-md-11">
  <%= content %>
</div>

app/views/shared/_errors.html.erb
<div class="alert alert-danger">
  <strong>错误</strong>
  <ul>
    <% @object.errors.full_messages.map do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_footer.html.erb
<div class="page-footer-inner">
   2014 &copy; Natware Soft.
</div>
<div class="page-footer-tools">
  <span class="go-top">
  <i class="fa fa-angle-up"></i>
  </span>
</div>

app/views/shared/_inbox.html.erb
<!-- BEGIN INBOX DROPDOWN -->
<li class="dropdown dropdown-extended dropdown-inbox" id="header_inbox_bar">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
  <i class="icon-envelope-open"></i>
  <span class="badge badge-default">
  4 </span>
  </a>
  <ul class="dropdown-menu">
    <li>
      <p>
         You have 12 new messages
      </p>
    </li>
    <li>
      <ul class="dropdown-menu-list scroller" style="height: 250px;">
        <li>
          <a href="inbox.html?a=view">
          <span class="photo">
          <img src="../assets/avatar2.jpg" alt=""/>
          </span>
          <span class="subject">
          <span class="from">
          Lisa Wong </span>
          <span class="time">
          Just Now </span>
          </span>
          <span class="message">
          Vivamus sed auctor nibh congue nibh. auctor nibh auctor nibh... </span>
          </a>
        </li>
        <li>
          <a href="inbox.html?a=view">
          <span class="photo">
          <img src="../assets/avatar3.jpg" alt=""/>
          </span>
          <span class="subject">
          <span class="from">
          Richard Doe </span>
          <span class="time">
          16 mins </span>
          </span>
          <span class="message">
          Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
          </a>
        </li>
        <li>
          <a href="inbox.html?a=view">
          <span class="photo">
          <img src="../assets/avatar1.jpg" alt=""/>
          </span>
          <span class="subject">
          <span class="from">
          Bob Nilson </span>
          <span class="time">
          2 hrs </span>
          </span>
          <span class="message">
          Vivamus sed nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
          </a>
        </li>
        <li>
          <a href="inbox.html?a=view">
          <span class="photo">
          <img src="../assets/avatar2.jpg" alt=""/>
          </span>
          <span class="subject">
          <span class="from">
          Lisa Wong </span>
          <span class="time">
          40 mins </span>
          </span>
          <span class="message">
          Vivamus sed auctor 40% nibh congue nibh... </span>
          </a>
        </li>
        <li>
          <a href="inbox.html?a=view">
          <span class="photo">
          <img src="../assets/avatar3.jpg" alt=""/>
          </span>
          <span class="subject">
          <span class="from">
          Richard Doe </span>
          <span class="time">
          46 mins </span>
          </span>
          <span class="message">
          Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
          </a>
        </li>
      </ul>
    </li>
    <li class="external">
      <a href="inbox.html">
      See all messages <i class="m-icon-swapright"></i>
      </a>
    </li>
  </ul>
</li>
<!-- END INBOX DROPDOWN -->

app/views/shared/_menu.html.erb
<ul class="nav navbar-nav">
  <li class="classic-menu-dropdown">
    <a id="menu_dashboard" href="/">
      控制台
    </a>
  </li>
  
  <li class="classic-menu-dropdown">
    <a data-toggle="dropdown" data-hover="dropdown" data-close-others="true" href="">
      订单<i class="fa fa-angle-down"></i>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "订单", orders_path, { id: "menu_orders" } %></li>
      <li><%= link_to "账号", users_path, { id: "menu_users" } %></li>
      <li><%= link_to "库存", cars_path, { id: "menu_cars" } %></li>
      <li><%= link_to "配件", accessories_path, { id: "menu_accessories" } %></li>
    </ul>
  </li>
</ul>

<% content_for :page_scripts do %>
<%= javascript_include_tag 'highlight_menu', 'data-turbolinks-track' => false %>
<% end %>

app/views/shared/_message.html.erb
<% unless flash[:alert].nil? %>
<div class="row">
  <div class="col-md-12">
    <div class="alert alert-danger">
      <strong>提醒</strong>
      <ul>
        <li><%= flash[:alert] %></li>
      </ul>
    </div>
    <% end %>

    <% unless flash[:notice].nil? %>
    <div class="alert alert-success">
      <strong>提醒</strong>
      <ul>
        <li><%= flash[:notice] %></li>
      </ul>
    </div>
    <% end %>

    <% unless flash[:error].nil? %>
    <div class="alert alert-danger">
      <strong>错误</strong>
      <ul>
        <li><%= flash[:error] %></li>
      </ul>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_notification.html.erb
<!-- BEGIN NOTIFICATION DROPDOWN -->
<li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
  <i class="icon-bell"></i>
  <span class="badge badge-default">
  7 </span>
  </a>
  <ul class="dropdown-menu">
    <li>
      <p>
         You have 14 new notifications
      </p>
    </li>
    <li>
      <ul class="dropdown-menu-list scroller" style="height: 250px;">
        <li>
          <a href="#">
          <span class="label label-sm label-icon label-success">
          <i class="fa fa-plus"></i>
          </span>
          New user registered. <span class="time">
          Just now </span>
          </a>
        </li>
        <li>
          <a href="#">
          <span class="label label-sm label-icon label-danger">
          <i class="fa fa-bolt"></i>
          </span>
          Server #12 overloaded. <span class="time">
          15 mins </span>
          </a>
        </li>
        <li>
          <a href="#">
          <span class="label label-sm label-icon label-warning">
          <i class="fa fa-bell-o"></i>
          </span>
          Server #2 not responding. <span class="time">
          22 mins </span>
          </a>
        </li>
        <li>
          <a href="#">
          <span class="label label-sm label-icon label-info">
          <i class="fa fa-bullhorn"></i>
          </span>
          Application error. <span class="time">
          40 mins </span>
          </a>
        </li>
        <li>
          <a href="#">
          <span class="label label-sm label-icon label-danger">
          <i class="fa fa-bolt"></i>
          </span>
          Database overloaded 68%. <span class="time">
          2 hrs </span>
          </a>
        </li>
        <li>
          <a href="#">
          <span class="label label-sm label-icon label-danger">
          <i class="fa fa-bolt"></i>
          </span>
          2 user IP blocked. <span class="time">
          5 hrs </span>
          </a>
        </li>
        <li>
          <a href="#">
          <span class="label label-sm label-icon label-warning">
          <i class="fa fa-bell-o"></i>
          </span>
          Storage Server #4 not responding. <span class="time">
          45 mins </span>
          </a>
        </li>
        <li>
          <a href="#">
          <span class="label label-sm label-icon label-info">
          <i class="fa fa-bullhorn"></i>
          </span>
          System Error. <span class="time">
          55 mins </span>
          </a>
        </li>
        <li>
          <a href="#">
          <span class="label label-sm label-icon label-danger">
          <i class="fa fa-bolt"></i>
          </span>
          Database overloaded 68%. <span class="time">
          2 hrs </span>
          </a>
        </li>
      </ul>
    </li>
    <li class="external">
      <a href="#">
      See all notifications <i class="m-icon-swapright"></i>
      </a>
    </li>
  </ul>
</li>
<!-- END NOTIFICATION DROPDOWN -->

app/views/shared/_page_title.html.erb
<div class="row">
  <div class="col-md-12">
    <!-- BEGIN PAGE TITLE & BREADCRUMB-->
    <h3 class="page-title">
    Dashboard <small>statistics and more</small>
    </h3>
    <ul class="page-breadcrumb breadcrumb">
      <li>
        <i class="fa fa-home"></i>
        <a href="index.html">Home</a>
        <i class="fa fa-angle-right"></i>
      </li>
      <li>
        <a href="#">Dashboard</a>
      </li>
      <li class="pull-right">
        <div id="dashboard-report-range" class="dashboard-date-range tooltips" data-placement="top" data-original-title="Change dashboard date range">
          <i class="icon-calendar"></i>
          <span></span>
          <i class="fa fa-angle-down"></i>
        </div>
      </li>
    </ul>
    <!-- END PAGE TITLE & BREADCRUMB-->
  </div>
</div>

app/views/shared/_progress_bar.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="progress">
      <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
        <span class="sr-only">
        20% Complete </span>
      </div>
    </div>
  </div>
</div>

app/views/shared/_task.html.erb
<!-- BEGIN TODO DROPDOWN -->
<li class="dropdown dropdown-extended dropdown-tasks" id="header_task_bar">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
  <i class="icon-calendar"></i>
  <span class="badge badge-default">
  3 </span>
  </a>
  <ul class="dropdown-menu extended tasks">
    <li>
      <p>
         You have 12 pending tasks
      </p>
    </li>
    <li>
      <ul class="dropdown-menu-list scroller" style="height: 250px;">
        <li>
          <a href="#">
          <span class="task">
          <span class="desc">
          New release v1.2 </span>
          <span class="percent">
          30% </span>
          </span>
          <span class="progress">
          <span style="width: 40%;" class="progress-bar progress-bar-success" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100">
          <span class="sr-only">
          40% Complete </span>
          </span>
          </span>
          </a>
        </li>
        <li>
          <a href="#">
          <span class="task">
          <span class="desc">
          Application deployment </span>
          <span class="percent">
          65% </span>
          </span>
          <span class="progress progress-striped">
          <span style="width: 65%;" class="progress-bar progress-bar-danger" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100">
          <span class="sr-only">
          65% Complete </span>
          </span>
          </span>
          </a>
        </li>
        <li>
          <a href="#">
          <span class="task">
          <span class="desc">
          Mobile app release </span>
          <span class="percent">
          98% </span>
          </span>
          <span class="progress">
          <span style="width: 98%;" class="progress-bar progress-bar-success" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100">
          <span class="sr-only">
          98% Complete </span>
          </span>
          </span>
          </a>
        </li>
        <li>
          <a href="#">
          <span class="task">
          <span class="desc">
          Database migration </span>
          <span class="percent">
          10% </span>
          </span>
          <span class="progress progress-striped">
          <span style="width: 10%;" class="progress-bar progress-bar-warning" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">
          <span class="sr-only">
          10% Complete </span>
          </span>
          </span>
          </a>
        </li>
        <li>
          <a href="#">
          <span class="task">
          <span class="desc">
          Web server upgrade </span>
          <span class="percent">
          58% </span>
          </span>
          <span class="progress progress-striped">
          <span style="width: 58%;" class="progress-bar progress-bar-info" aria-valuenow="58" aria-valuemin="0" aria-valuemax="100">
          <span class="sr-only">
          58% Complete </span>
          </span>
          </span>
          </a>
        </li>
        <li>
          <a href="#">
          <span class="task">
          <span class="desc">
          Mobile development </span>
          <span class="percent">
          85% </span>
          </span>
          <span class="progress progress-striped">
          <span style="width: 85%;" class="progress-bar progress-bar-success" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100">
          <span class="sr-only">
          85% Complete </span>
          </span>
          </span>
          </a>
        </li>
        <li>
          <a href="#">
          <span class="task">
          <span class="desc">
          New UI release </span>
          <span class="percent">
          18% </span>
          </span>
          <span class="progress progress-striped">
          <span style="width: 18%;" class="progress-bar progress-bar-important" aria-valuenow="18" aria-valuemin="0" aria-valuemax="100">
          <span class="sr-only">
          18% Complete </span>
          </span>
          </span>
          </a>
        </li>
      </ul>
    </li>
    <li class="external">
      <a href="#">
      See all tasks <i class="m-icon-swapright"></i>
      </a>
    </li>
  </ul>
</li>
<!-- END TODO DROPDOWN -->

app/views/shared/_version.html.erb
<h4 class="form-section"><%=title %>日志</h4>

<div class="table-responsive">
  <table class="table table-hover table-bordered">
    <% item.versions.reverse.each do |v|%>
    <thead>
    <tr>
      <td class="col-md-1">操作者:</td>
      <td class="col-md-3"><%= User.find(v.whodunnit).name unless v.whodunnit.blank? %></td>
      <td class="col-md-1">动作:</td>
      <td class="col-md-3"><%= case v.event 
                  when 'update' 
                    '更新'
                  when 'create' 
                    '创建' 
                  end %></td>
      <td class="col-md-1">时间:</td>
      <td class="col-md-2"><%= v.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
      <td class="col-md-1"><a data-toggle="collapse" data-toggle="collapse" data-parent="#accordion" href="#collapse_<%= v.id %>">详情</a></td>
    </tr>
    </thead>
    
    <tbody>
    <tr>
      <td colspan="7">
      <div id="collapse_<%= v.id %>" class="panel-collapse collapse">
        <div class="panel-body">
          <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <td class="col-md-2">栏位</td>
              <td class="col-md-5">更改前</td>
              <td class="col-md-5">更改后</td>
            </tr>
          </thead>
          <tbody>
            <% v.changeset.each do |c| %>
            <tr>
              <td><%= label item.class.to_s.underscore.to_sym, c[0].to_sym %></td>
              <td><%= c[1][0] %></td>
              <td><%= c[1][1] %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        </div>
      </div>
      </td>
    </tr>
    </tbody>
    <% end %>
  </table>
</div>