config/routes.rb
Rails.application.routes.draw do
  resources :payments

  resources :order_accessories

  resources :accessories

  resources :orders

  resources :cars

  devise_for :users
  resources :users

  root 'orders#index'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  include ModelConcerns::Sequenable
  sequence :PY
  
  belongs_to :order

  validates :amount, presence: true
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  load_and_authorize_resource
  
  def index
    @payments = @payments.order("id desc").page(params[:page])
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def payment_params
    params.require(:payment).permit(:order_id, :amount, :paid_at, :type, :card_no, :bank, :no)
  end
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :paid_at %><br>
    <%= f.datetime_select :paid_at %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :card_no %><br>
    <%= f.text_field :card_no %>
  </div>
  <div class="field">
    <%= f.label :bank %><br>
    <%= f.text_field :bank %>
  </div>
  <div class="field">
    <%= f.label :no %><br>
    <%= f.text_field :no %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Amount</th>
      <th>Paid at</th>
      <th>Type</th>
      <th>Card no</th>
      <th>Bank</th>
      <th>No</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.order_id %></td>
        <td><%= payment.amount %></td>
        <td><%= payment.paid_at %></td>
        <td><%= payment.type %></td>
        <td><%= payment.card_no %></td>
        <td><%= payment.bank %></td>
        <td><%= payment.no %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @payment.order_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>Paid at:</strong>
  <%= @payment.paid_at %>
</p>

<p>
  <strong>Type:</strong>
  <%= @payment.type %>
</p>

<p>
  <strong>Card no:</strong>
  <%= @payment.card_no %>
</p>

<p>
  <strong>Bank:</strong>
  <%= @payment.bank %>
</p>

<p>
  <strong>No:</strong>
  <%= @payment.no %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>